### ISSUE TITLE
Missing a script

### ISSUE THREAD

**Issue by Roudiroudi** [rumart/vSpherePerfData#5]
Hello Rudi,

First thank you for your amazing work and sharing us to it.It seems you re talking about a script for update vcsa in the dashboard but the link where your  are pointing in your webpage is going to 404 error.is it possible for you to upload it please ?
Thank you

Richard

**Comment by rumart** [comment]
Hi Richard
Glad you find it useful.
I've uploaded the missing script. Thanks for reaching out.

/Rudi
